### PR TITLE
Update nl.md

### PR DESCRIPTION
**Pull request by dcaliste**
Some typos corrections and also one or two questions put in bold witrhin the text. Feel free to start discussing these points in the review.

### CODE REVIEW

**Comment by poetaster** [comment]
Thanks! 

So, the first question, why the API note, I was thinking of readers not knowing the meaning of API. This is not that likely for NLnet, but I was being cautious. 

The second question we could easily expand in-line. The point is that user specific data would need to be supplied to each service provider if they were to apply for, for instance, developer keys. Mapbox has quite a bit of data on me ;) In the keypeer scheme, the api providers don't obtain any user data. That should be clarified.

**Comment by rinigus** [comment]
I am writing it here for visibility: abstract is 1200 chars, not words.

**Review by poetaster — DISMISSED** [review]
Just remove the bold questions and I'll merge and:
1. reduce the API explication
2. expand in a sentance on the privacy dimension.

**Comment by rinigus** [comment]
Service providers do get data on what you were doing on their service (search, tiles, ...). But, they don't know who you are, unless it is possible to derive from their data

**Comment by poetaster** [comment]
> 



> I am writing it here for visibility: abstract is 1200 chars, not words.

Thanks, missed that and was so happy with my wordcount. Sigh. In that case, I could just as well merge and start reducing.

**Comment by dcaliste** [comment]
I've removed the questions and just keep the typos and some rephrasing.

Thanks @rinigus for reminding us that the abstract requires a major rework…

@poetaster should I wait for you reorganising the document, or can I start proposing something ?

**Comment by poetaster** [comment]
Ok, I'm going to merge this in. Then I will copy the corrections to the posts/introduction document. Then I will submit the MUCH shorter abstract.

**Review by poetaster — APPROVED** [review]
We need to collapse this down so I'll add the relevant changes to the introduction document.

**Comment by poetaster** [comment]
> I've removed the questions and just keep the typos and some rephrasing.
> 
> Thanks @rinigus for reminding us that the abstract requires a major rework…
> 
> @poetaster should I wait for you reorganising the document, or can I start proposing something ?

I've already done a short version which I'll commit now.

**Comment by poetaster** [comment]
> I've removed the questions and just keep the typos and some rephrasing.
> 
> Thanks @rinigus for reminding us that the abstract requires a major rework…
> 
> @poetaster should I wait for you reorganising the document, or can I start proposing something ?

I've added an abstract.md document to make it easy to track charcount while working on it and put the current version in nl.md . I'm going to look at adding some supporting documents (like diagrams) and welcome contributions.

**Pull request merged**
