### PR TITLE
Some abstract polishing.

### PR DESCRIPTION
**Pull request by dcaliste**
Difficult job to write something clear within 1200 characters… I'm wondering how the example could underline the keypeer value while now it is only stating current situation letting the reader understand the advantage…

Besides, I think that the main text (nl.md) should be kept in its previous full version, shouldn't it ? In the submission page, they mention that we can add a full blown document to the proposal. This nl.md should be this full document right ? With much more details than in the web abstract.

What do you think @poetaster ?

### CODE REVIEW

**Comment by poetaster** [comment]
> Difficult job to write something clear within 1200 characters… I'm wondering how the example could underline the keypeer value while now it is only stating current situation letting the reader understand the advantage…
> 

Yes, it's tight.


> Besides, I think that the main text (nl.md) should be kept in its previous full version, shouldn't it ? In the submission page, they mention that we can add a full blown document to the proposal. This nl.md should be this full document right ? With much more details than in the web abstract.

The long form Abstract was basically the posts/introduction.md text. so, I'd include that full page since you can supply additional information (attach html doc). So, the long abstract is retained.

> 
> What do you think @poetaster ?

Does that seem ok? I'm also juggling deploying the website which distracts a bit from the core task.

**Review by poetaster — APPROVED** [review]
I really don't like software being made plural. I understand why people do it. But software, as an abstraction, is plural. Like math. Or agriculture. I'll try to ignore it.

**Comment by dcaliste** [comment]
> But software, as an abstraction, is plural. Like math. Or agriculture. I'll try to ignore it.

Oh, I see. I can remove it !

**Comment by dcaliste** [comment]
> So, the long abstract is retained.

Ah sure, fine then. I missed this one and was focussed on nl.md.

**Comment by poetaster** [comment]
You don't have to. I've argued with an Englishman (I'm Canadian) who insisted on 'maths' ... we did not agree but I'm a poetaster :) 

 By including the introduction I meant as produced: https://keypeer.org/introduction.html but the text is the same as was in the old abstract.

**Pull request merged**
